### ISSUE TITLE
Custom Font not working

### ISSUE THREAD

**Issue by Dave181295** [lascic/UIOnboarding#13]
```

 static func setUpSecondTitleLine() -> NSMutableAttributedString {
        .init(string: Bundle.main.displayName! ,  attributes: [
         
            .foregroundColor: UIColor(Color.TintColor) ,
            .font : UIFont(name: "MADECanvas", size: 16)!,
        ])
    }

```

The font is found as I got no crash

**Comment by Dave181295** [comment]
Any news friends?

**Comment by lascic** [comment]
I have replicated your situation and the issue lies in the onboarding view controller overwriting custom fonts with the system font.
I designed this UI library to prevent as much customising as possible to keep the consistency across the whole system.

I have put the issue on my list and will look into it. In the meantime, you can clone the repo, add the files to your project and manually change the font attributes where needed. Hope that helps for now.

Thanks again for your comment.

**Comment by Dave181295** [comment]
Thanks for your fast reply, I will maybe even for the repo to add a default parameter for custom fonts.

**Comment by Dave181295** [comment]
Hello, we failed to fix it as we got multiple conflicts with ``UIKIT``
you know the project more than anyone, please fix it asap when you are available.
we love your library


Greetings,

**Comment by Dave181295** [comment]
Btw, it would looks better to make the subtitles (SecondLines) more small and have more spacing between the firstTitle
Standart UI/UX for mobile apps

**Comment by lascic** [comment]
Appreciate your feedback. Let me go through the issue. As for the design specs of the feature labels, I'll make that an option to customize in the future.

**Comment by lascic** [comment]
Just pushed v2.0.2 to the public. Let me know if any issues occur.
